version: 0.0
os: linux
files:
 - source: /
   destination: /home/ubuntu/project/loserrrrr/
hooks:
 BeforeInstall:
   - location: deploy_scripts/install_dependencies.sh
     timeout: 300
     runas: ubuntu
 AfterInstall:
   - location: deploy_scripts/change_permissions.sh
     timeout: 300
     runas: root
 ApplicationStart:
   - location: deploy_scripts/start_server.sh
     timeout: 300
     runas: ubuntu
 ApplicationStop:
   - location: deploy_scripts/stop_server.sh
     timeout: 300
     runas: ubuntu